jobs:

# Replace params / app_name with your heroku app name
- name: ci
  plan:
  - aggregate:
    - get: heroku-pipeline-app
    - get: heroku-pipeline-infra
      trigger: true
  - task: sync_heroku
    file: heroku-example/concourse/heroku_sync.yml
    input_mapping: {source: heroku-example-app}
    params:
      app_name: glennbech-heroku-example
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_token))

resources:

# Replace with your own repository
- name: heroku-pipeline-app
  type: git
  source:
      uri: git@github.com:PGR301-2018/heroku-pipeline-app.git
      branch: master
      private_key: ((deploy_key))

# Replace with your own repository
- name: heroku-pipeline-infra
  type: git
  source:
      uri: git@github.com:PGR301-2018/heroku-pipeline-infra.git
      branch: master
      private_key: ((deploy-key-app))
